version: "3.6"

services:
  db:
    image: postgres
    ports:
      - 5460:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /opt/peruvian-food-api-postgres:/var/lib/postgresql/data
